apiVersion: 1

datasources:
  - name: PostgreSQL-MathSolver
    type: postgres
    access: proxy
    url: postgres:5432
    database: math_solver_analytics
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      sslmode: disable
      maxOpenConns: 50
      maxIdleConns: 50
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false
    isDefault: true
    editable: true
